
repos:
    - repo: local
      hooks:
        - id: YAPF 
          name: YAPF ğŸ§¹
          entry: zsh -c 'yapf --in-place *.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: isort 
          name: isort ğŸ“š
          entry: zsh -c 'isort .'
          language: system
          always_run: true
          pass_filenames: true
        - id: autoflake 
          name: autoflake â„ï¸
          entry: zsh -c 'autoflake --in-place --remove-unused-variables --remove-all-unused-imports *.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: pylint 
          name: pylint ğŸ”
          entry: zsh -c 'pylint --fail-under=7 *.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: pytest 
          name: Unit Tests ğŸ§ª
          entry: zsh -c 'pytest test_helpers.py'
          language: system
          always_run: true
          pass_filenames: false