
repos:
    - repo: local
      hooks:
        - id: YAPF
          name: YAPF ğŸ§¹
          entry: bash -c 'yapf --in-place **/*.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: isort
          name: isort ğŸ“š
          entry: bash -c 'isort ./src/'
          language: system
          always_run: true
          pass_filenames: true
        - id: autoflake
          name: autoflake â„ï¸
          entry: bash -c 'autoflake --in-place --remove-unused-variables --remove-all-unused-imports **/*.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: pylint
          name: pylint ğŸ”
          entry: bash -c 'pylint --fail-under=7 **/*.py'
          language: system
          always_run: true
          pass_filenames: true